# Generated by Django 5.2.1 on 2025-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_am_sign_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sign_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sign_out_time',
        ),
    ]
